/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1beta1 "knative.dev/eventing-rabbitmq/pkg/apis/messaging/v1beta1"
)

// FakeRabbitmqChannels implements RabbitmqChannelInterface
type FakeRabbitmqChannels struct {
	Fake *FakeMessagingV1beta1
	ns   string
}

var rabbitmqchannelsResource = schema.GroupVersionResource{Group: "messaging.knative.dev", Version: "v1beta1", Resource: "rabbitmqchannels"}

var rabbitmqchannelsKind = schema.GroupVersionKind{Group: "messaging.knative.dev", Version: "v1beta1", Kind: "RabbitmqChannel"}

// Get takes name of the rabbitmqChannel, and returns the corresponding rabbitmqChannel object, and an error if there is any.
func (c *FakeRabbitmqChannels) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.RabbitmqChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rabbitmqchannelsResource, c.ns, name), &v1beta1.RabbitmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RabbitmqChannel), err
}

// List takes label and field selectors, and returns the list of RabbitmqChannels that match those selectors.
func (c *FakeRabbitmqChannels) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.RabbitmqChannelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rabbitmqchannelsResource, rabbitmqchannelsKind, c.ns, opts), &v1beta1.RabbitmqChannelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.RabbitmqChannelList{ListMeta: obj.(*v1beta1.RabbitmqChannelList).ListMeta}
	for _, item := range obj.(*v1beta1.RabbitmqChannelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rabbitmqChannels.
func (c *FakeRabbitmqChannels) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rabbitmqchannelsResource, c.ns, opts))

}

// Create takes the representation of a rabbitmqChannel and creates it.  Returns the server's representation of the rabbitmqChannel, and an error, if there is any.
func (c *FakeRabbitmqChannels) Create(ctx context.Context, rabbitmqChannel *v1beta1.RabbitmqChannel, opts v1.CreateOptions) (result *v1beta1.RabbitmqChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rabbitmqchannelsResource, c.ns, rabbitmqChannel), &v1beta1.RabbitmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RabbitmqChannel), err
}

// Update takes the representation of a rabbitmqChannel and updates it. Returns the server's representation of the rabbitmqChannel, and an error, if there is any.
func (c *FakeRabbitmqChannels) Update(ctx context.Context, rabbitmqChannel *v1beta1.RabbitmqChannel, opts v1.UpdateOptions) (result *v1beta1.RabbitmqChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rabbitmqchannelsResource, c.ns, rabbitmqChannel), &v1beta1.RabbitmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RabbitmqChannel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRabbitmqChannels) UpdateStatus(ctx context.Context, rabbitmqChannel *v1beta1.RabbitmqChannel, opts v1.UpdateOptions) (*v1beta1.RabbitmqChannel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rabbitmqchannelsResource, "status", c.ns, rabbitmqChannel), &v1beta1.RabbitmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RabbitmqChannel), err
}

// Delete takes name of the rabbitmqChannel and deletes it. Returns an error if one occurs.
func (c *FakeRabbitmqChannels) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rabbitmqchannelsResource, c.ns, name), &v1beta1.RabbitmqChannel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRabbitmqChannels) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rabbitmqchannelsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1beta1.RabbitmqChannelList{})
	return err
}

// Patch applies the patch and returns the patched rabbitmqChannel.
func (c *FakeRabbitmqChannels) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.RabbitmqChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rabbitmqchannelsResource, c.ns, name, pt, data, subresources...), &v1beta1.RabbitmqChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.RabbitmqChannel), err
}
