# This is an example on how to build a standalone rabbitmq cluster on gke
# Do NOT use this in your production environment!!
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management-ui
spec:
  type: LoadBalancer
  ports:
  - port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    run: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-protocol
spec:
  type: LoadBalancer
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    run: rabbitmq
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:3-management
    name: rabbitmq
    ports:
    - containerPort: 15672
    - containerPort: 5672
  restartPolicy: Never
