apiVersion: v1
kind: Pod
metadata:
  name: event-sender
  namespace: trigger-demo
spec:
  restartPolicy: Never
  containers:
    - name: event-sender
      image: ko://knative.dev/eventing-rabbitmq/samples/broker-trigger/trigger-customizations/event-sender
      args:
        - --sink=http://default-broker-ingress.trigger-demo.svc.cluster.local
        - --event={"specversion":"1.0","type":"SenderEvent","source":"Sender","datacontenttype":"application/json","data":{}}
        - --num-messages=10
