apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: rabbitstats
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ko://knative.dev/eventing-rabbitmq/cmd/rabbitstats
