apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: source-demo
spec:
  brokers: "rabbitmq:5672/"
  topic: ""
  user:
    secretKeyRef:
      name: rabbitmq-default-user
      key: username
  password:
    secretKeyRef:
      name: rabbitmq-default-user
      key: password
  channelConfig:
    # Value must be between 1 and 1000
    # A value of 1 RabbitMQ Source behaves as a FIFO queue
    # Values above 1 break message ordering guarantees and can be seen as more performance oriented
    # parallelism: 10
    globalQos: false
  exchangeConfig:
    name: "eventing-rabbitmq-source"
    type: "fanout"
    durable: false
    autoDelete: false
    internal: false
    nowait: false
  queueConfig:
    name: "eventing-rabbitmq-source"
    routingKey: ""
    durable: false
    # TODO: Why is the queue not deleted 30 minutes after the source is deleted?
    # https://github.com/knative-sandbox/eventing-rabbitmq/issues/528
    autoDelete: true
    # TODO: SHORT-TERM FIX
    # Ensures that the queue is deleted when the Source is deleted
    # While exclusive is true, channelConfig.parallelism cannot be updated
    exclusive: true
    nowait: false
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: rabbitmq-source-sink
      namespace: source-demo
