/*
Copyright 2020 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	messagingv1beta1 "knative.dev/eventing-rabbitmq/pkg/apis/messaging/v1beta1"
	versioned "knative.dev/eventing-rabbitmq/pkg/client/clientset/versioned"
	internalinterfaces "knative.dev/eventing-rabbitmq/pkg/client/informers/externalversions/internalinterfaces"
	v1beta1 "knative.dev/eventing-rabbitmq/pkg/client/listers/messaging/v1beta1"
)

// RabbitmqChannelInformer provides access to a shared informer and lister for
// RabbitmqChannels.
type RabbitmqChannelInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1beta1.RabbitmqChannelLister
}

type rabbitmqChannelInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRabbitmqChannelInformer constructs a new informer for RabbitmqChannel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRabbitmqChannelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRabbitmqChannelInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRabbitmqChannelInformer constructs a new informer for RabbitmqChannel type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRabbitmqChannelInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MessagingV1beta1().RabbitmqChannels(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MessagingV1beta1().RabbitmqChannels(namespace).Watch(context.TODO(), options)
			},
		},
		&messagingv1beta1.RabbitmqChannel{},
		resyncPeriod,
		indexers,
	)
}

func (f *rabbitmqChannelInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRabbitmqChannelInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rabbitmqChannelInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&messagingv1beta1.RabbitmqChannel{}, f.defaultInformer)
}

func (f *rabbitmqChannelInformer) Lister() v1beta1.RabbitmqChannelLister {
	return v1beta1.NewRabbitmqChannelLister(f.Informer().GetIndexer())
}
