apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: default
  namespace: retry-config-sample
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: RabbitmqBrokerConfig
    name: default-config
  delivery:
    deadLetterSink:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: event-display
        namespace: retry-config-sample
    # this retry config is going to be applied for the messages going to the Broker's DLQ
    retry: 4
    backoffPolicy: "linear"
    backoffDelay: "PT1S"
