---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  name: ping-broker-rabbitmq
  namespace: ping
  annotations:
    eventing.knative.dev/broker.class: RabbitMQBroker
spec:
  config:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rabbitmq
    namespace: knative-eventing
---
apiVersion: sources.knative.dev/v1
kind: PingSource
metadata:
  name: ping-source
  namespace: ping
spec:
  schedule: "*/1 * * * *"
  data: '{"responsecode": 200}'
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: ping-broker-rabbitmq
      namespace: ping
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ping-cloudevents-player-rabbitmq
  namespace: ping
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ruromero/cloudevents-player:latest
          env:
            - name: BROKER_URL
              value: http://ping-broker-rabbitmq-broker-ingress.ping.svc.cluster.local
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: ping-cloudevents-player-trigger-rabbitmq
  namespace: ping
spec:
  broker: ping-broker-rabbitmq
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: ping-cloudevents-player-rabbitmq
      namespace: ping
