apiVersion: sources.eventing.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: rabbitsource
spec:
  brokers: RABBITMQ_BROKERS
  topic: RABBITMQ_TOPIC
  retry: 5
  backoffPolicy: "linear"
  backoffDelay: "50ms"
  user:
    secretKeyRef:
      name: RABBITMQ_USER
      key: RABBITMQ_USER
  password:
    secretKeyRef:
      name: RABBITMQ_PASSWORD
      key: RABBITMQ_PASSWORD
  connectionSecret:
    name: RABBITMQ_CONNECTION_SECRET
  exchangeConfig:
    name: RABBITMQ_EXCHANGE_CONFIG_NAME
    type: RABBITMQ_EXCHANGE_CONFIG_TYPE
    durable: RABBITMQ_EXCHANGE_CONFIG_DURABLE
    autoDelete: RABBITMQ_EXCHANGE_CONFIG_AUTO_DELETE
  queueConfig:
    name: RABBITMQ_QUEUE_CONFIG_NAME
    routingKey: RABBITMQ_ROUTING_KEY
    durable: RABBITMQ_QUEUE_CONFIG_DURABLE
    autoDelete: RABBITMQ_QUEUE_CONFIG_AUTO_DELETE
  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
    namespace: rabbitsource
