
:toc:
:toc-placement!:
= RabbitMQ Source

The RabbitMQ source translates messages on a RabbitMQ exchange to CloudEvents,
which can then be sent to other Knative Eventing components (Brokers, Channels,
or other https://knative.dev/docs/eventing/#event-consumers[Addressable]
objects) over HTTP. The RabbitMQ source can bind to an existing RabbitMQ
exchange, or create a new exchange if required.

toc::[]


== Getting started

=== Install

* Install the RabbitMQ source from the nightly build (requires cluster administrator):

[source,sh]
----
kubectl apply -f https://storage.googleapis.com/knative-nightly/eventing-rabbitmq/latest/rabbitmq-source.yaml
----

=== Create a `RabbitmqSource`

[source,sh]
----
kubectl create secret generic rabbitmq-secret \
  --from-literal=user=rabbit-user \
  --from-file=password=/tmp/password
----

Then `kubectl apply` the following object to send events to the `event-display` service:

[source,yaml]
----
apiVersion: sources.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
spec:
  brokers: "rabbitmq:5672/"
  user:
    secretKeyRef:
      name: "rabbitmq-secret"
      key: "user"
  password:
    secretKeyRef:
      name: "rabbitmq-secret"
      key: "password"
  exchange_config:
    type: "fanout"
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
----

=== Publish and receive a message:

Using https://www.rabbitmq.com/management-cli.html[`rabbitmqadmin`]:


[source,shell]
----
rabbitmqadmin publish exchange=amq.fanout payload="Hello rabbitmq!"
----

.CloudEvents JSON format
[source,json]
----
{
  "specversion": "1.0",
  "type": "dev.knative.rabbitmq.event",
  "source": "/apis/v1/namespaces/default/rabbitmqsources/rabbitmq-source",
  "id": "f00c1f52-33a1-4d3d-993f-750f20c804da",
  "time": "2020-12-18T01:15:20.450860898Z",
  "subject": "",
  "datacontenttype": "application/json",
  "key": "",
  "data": "Hello rabbitmq!"
}
----

== Reference

=== Prerequisites

* A https://www.rabbitmq.com/[RabbitMQ] installation. On Kubernetes, you can use
https://www.rabbitmq.com/kubernetes/operator/operator-overview.html[the RabbitMQ
operator] to set up a RabbitMQ installation.

* An understanding of RabbitMQ concepts like Brokers, Exchanges, and Queues.

=== Event schema

All messages received by the RabbitMQ source are published with the following
schema:

.Event attributes
|===
| Attribute | Value | Notes

| `type` | `dev.knative.rabbitmq.event` |
| `source` | `/apis/v1/namespace/*$NS*/rabbitmqsources/*$NAME*#*$TOPIC*`
   | `NS`, `NAME` and `TOPIC` are derived from the source configuration
| `id` | A unique ID | This uses the `MessageId` if available, and a UUID otherwise
| `subject` | The ID of the message | Empty string if no message ID is present
| `datacontenttype` | `application/json` | Currently static
| `key` | The ID of the message | Empty string if no message ID is present
|===

The payload of the event is set to the data content of the message.

=== Resource fields

// Note: this could link to generated documentation if that's easy to do...

`RabbitmqSources` are Kubernetes objects. In addition to the standard Kubernetes
`apiVersion`, `kind`, and `metadata`, they have the following `spec` fields:

:optional: *

.Source parameters
|===
| Field | Value

| `spec.brokers` | Host+Port of the Broker, with a trailing "/"
| `user.secretKeyRef` | Username for Broker authentication; field `key` in a Kubernetes Secret named `name`
| `password.secretKeyRef` | Password for Broker authentication; field `key` in a Kubernetes Secret named `name`
| `topic` | The topic for the exchange
| `exchange_config` | Settings for the exchange
| `exchange_config.type` | https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges[Exchange type]. Can be `fanout`, `direct`, `topic`, `match` or `headers`
| `exchange_config.durable` {optional} | Boolean
| `exchange_config.auto_deleted` {optional} | Boolean
| `exchange_config.internal` {optional} | Boolean
| `exchange_config.nowait` {optional} | Boolean
| `queue_config` {optional} | Settings for the queue
| `queue_config.name` {optional} | Name of the queue (may be empty)
| `queue_config.routing_key` {optional} | Routing key for the queue
| `queue_config.durable` {optional} | Boolean
| `queue_config.delete_when_unused` {optional} | Boolean
| `queue_config.exclusive` {optional} | Boolean
| `queue_config.nowait` {optional} | Boolean
| `sink` | A reference to an https://knative.dev/docs/eventing/#event-consumers[Addressable] Kubernetes object
|===

{optional} These attributes are optional.

Note that many parameters do not need to be specified. Unspecified optional
parameters will be defaulted to `false` or `""` (empty string).

The source will provide output information about readiness or errors via the
`status` field on the object once it has been created in the cluster.

// TODO: should we have error documentation?

=== Debugging tips

TODO: write up troubleshooting steps (`status.condition` values and other places to look to debug issues).

=== Configuration options

The standard
https://github.com/knative/eventing/blob/master/config/core/configmaps/observability.yaml[`config-observability`]
and
https://github.com/knative/eventing/blob/master/config/core/configmaps/logging.yaml[`config-logging`]
ConfigMaps may be used to manage the logging and metrics configuration.

== Additional Resources

* The https://www.rabbitmq.com/kubernetes/operator/operator-overview.html[RabbitMQ Operator for Kubernetes] can be handy for running RabbitMQ on Kubernetes.