apiVersion: sources.eventing.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: rabbitsource
spec:
  brokers: RABBITMQ_BROKERS
  topic: RABBITMQ_TOPIC
  user:
    secretKeyRef:
      name: RABBITMQ_USER
      key: RABBITMQ_USER
  password:
    secretKeyRef:
      name: RABBITMQ_PASSWORD
      key: RABBITMQ_PASSWORD
  exchangeConfig:
    name: RABBITMQ_EXCHANGE_CONFIG_NAME
    type: RABBITMQ_EXCHANGE_CONFIG_TYPE
    durable: RABBITMQ_EXCHANGE_CONFIG_DURABLE
    autoDelete: RABBITMQ_EXCHANGE_CONFIG_AUTO_DELETE
    internal: RABBITMQ_EXCHANGE_CONFIG_INTERNAL
    nowait: RABBITMQ_EXCHANGE_CONFIG_NOWAIT
  queueConfig:
    name: RABBITMQ_QUEUE_CONFIG_NAME
    routingKey: RABBITMQ_ROUTING_KEY
    durable: RABBITMQ_QUEUE_CONFIG_DURABLE
    autoDelete: RABBITMQ_QUEUE_CONFIG_AUTO_DELETE
    exclusive: RABBITMQ_QUEUE_CONFIG_EXCLUSIVE
    nowait: RABBITMQ_QUEUE_CONFIG_NOWAIT

  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
    namespace: rabbitsource
