apiVersion: sources.eventing.knative.dev/v1alpha1
kind: RabbitmqSource
metadata:
  name: rabbitmq-source
  namespace: rabbitsource
spec:
  brokers: RABBITMQ_BROKERS
  topic: RABBITMQ_TOPIC
  user:
    secretKeyRef:
      name: RABBITMQ_USER
      key: RABBITMQ_USER
  password:
    secretKeyRef:
      name: RABBITMQ_PASSWORD
      key: RABBITMQ_PASSWORD
  exchangeConfig:
    name: RABBITMQ_exchangeConfig_NAME
    type: RABBITMQ_exchangeConfig_TYPE
    durable: RABBITMQ_exchangeConfig_DURABLE
    autoDelete: RABBITMQ_exchangeConfig_AUTO_DELETED
    internal: RABBITMQ_exchangeConfig_INTERNAL
    nowait: RABBITMQ_exchangeConfig_NOWAIT
  queueConfig:
    name: RABBITMQ_queueConfig_NAME
    routingKey: RABBITMQ_ROUTING_KEY
    durable: RABBITMQ_queueConfig_DURABLE
    autoDelete: RABBITMQ_queueConfig_AUTO_DELETED
    exclusive: RABBITMQ_queueConfig_EXCLUSIVE
    nowait: RABBITMQ_queueConfig_NOWAIT

  sink:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: event-display
    namespace: rabbitsource
